chat/urls.py
# chat/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

drf/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import url, include
from django.conf import settings # new
from django.conf.urls.static import static # new

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls')),
    url('employee/', include('employee.urls')),
    url('api/v1/', include('employee.api_urls')),
    url('api/v2/', include('polls.api_urls')),
    url('api/v3/', include('polls.api_urls_v3')),
    url('image/', include('image_processor.urls')), # new
   # url(r'api/v1/auth/login/', LoginView.as_view()),
]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.conf.urls import url

from . import views
app_name = 'polls'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='details'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.voting, name='voting'),
]

snippets/urls.py
from django.conf.urls import url

from . import views
app_name = 'snippet'

urlpatterns = [
    url('hello/',  views.hello),    
]

chat/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

polls/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils import timezone

import datetime


class Question(models.Model):
    question_text = models.CharField(max_length=200, unique=True)
    pub_date = models.DateTimeField('date published', default=timezone.now)

    status = models.CharField(default='inactive', max_length=10)

    def __str__(self):
        return self.question_text

    def is_recent_publish(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question,
                                 on_delete=models.CASCADE, null=False)
    choice_text = models.CharField(max_length=200, null=False)
    votes = models.IntegerField(default=0)

    class Meta:
        unique_together = ['question', 'choice_text']

    def __str__(self):
        return self.choice_text

snippets/models.py
from django.db import models
from pygments.lexers import get_all_lexers
from pygments.styles import get_all_styles

LEXERS = [item for item in get_all_lexers() if item[1]]
LANGUAGE_CHOICES = sorted([(item[1][0], item[0]) for item in LEXERS])
STYLE_CHOICES = sorted([(item, item) for item in get_all_styles()])


class Snippet(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=100, blank=True, default='')
    code = models.TextField()
    linenos = models.BooleanField(default=False)
    language = models.CharField(choices=LANGUAGE_CHOICES, default='python', max_length=100)
    style = models.CharField(choices=STYLE_CHOICES, default='friendly', max_length=100)

    class Meta:
        ordering = ['created']

chat/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
# chat/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'chat/index.html', {})

polls/views.py
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from .models import Question
from django.shortcuts import render, get_object_or_404
from django.views import generic
from rest_framework.parsers import JSONParser
from django.views.decorators.csrf import csrf_exempt
from .models import Choice
from polls.serializer import QuestionSerializer

from rest_framework.views import APIView
from rest_framework.response import Response


class pollAPIView(APIView):
    def get(self, request):
        questions = Question.objects.all()
        serializer = QuestionSerializer(questions, many=True)
        return Response(serializer.data)

    def post(self, request):
        data = request.data
        serializer = QuestionSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=201)
        else:
            return JsonResponse(serializer.errors, status=400)


@csrf_exempt
def poll(request):
    if (request.method == 'POST'):
        # convert post data to json by jsonParser from rest_framework
        json_parser = JSONParser()
        data = json_parser.parse(request)
        serializer = QuestionSerializer(data=data)

        if serializer.is_valid():
            serializer.save()
            return JsonResponse(serializer.data, status=201)
        else:
            return JsonResponse(serializer.errors, status=400)
    else:
        questions = Question.objects.all()
        serializer = QuestionSerializer(questions, many=True)
        return JsonResponse(serializer.data, safe=False)


@csrf_exempt
def poll_details(request, nana_id):
    try:
        instance = Question.objects.get(id=nana_id)
    except Question.DoesNotExist:
        return JsonResponse({"error": "Doesn't exist"}, status=404)
    if(request.method == 'GET'):
        serializer = QuestionSerializer(instance)
        return JsonResponse(serializer.data)

    #     if serializer.is_valid():
    #         print ('uu')
    #         serializer.save()
    #         return JsonResponse(serializer.data, status=201)
    #     else:
    #         print ('jhvhv')
    #         return JsonResponse(serializer.errors, status=400)
    # else:
    #     print ('as')
    #     questions = Question.objects.all()
    #     serializer = QuestionSerializer(questions, many=True)
    #     return JsonResponse(serializer.data, safe=False)


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/details.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     template = loader.get_template('polls/index.html')
#     context = {
#         'latest_question_list': latest_question_list,
#     }
#     return HttpResponse(template.render(context, request))

# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     context = {'latest_question_list': latest_question_list}
#     return render(request, 'polls/index.html', context)

# def details(request, question_id):
#     try:
#         q = Question.objects.get(pk=question_id)
#     except Question.DoesNotExist:
#         raise Http404("Questions does't exist")
#     return render(request, 'polls/details.html', {'question': q})

# def details(request, question_id):
#     q = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/details.html', {'question': q})
#
# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/results.html', {'question': question})

def voting(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results',
                                            args=(question.id,)))

snippets/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponse    

def hello(request):    
    return HttpResponse('<h1>This is Http GET request.</h1>')    

chat/templates/chat/index.html
<!-- chat/templates/chat/index.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Rooms</title>
</head>
<body>
    What chat room would you like to enter?<br/>
    <input id="room-name-input" type="text" size="100"/><br/>
    <input id="room-name-submit" type="button" value="Enter"/>

    <script>
        document.querySelector('#room-name-input').focus();
        document.querySelector('#room-name-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#room-name-submit').click();
            }
        };

        document.querySelector('#room-name-submit').onclick = function(e) {
            var roomName = document.querySelector('#room-name-input').value;
            window.location.pathname = '/chat/' + roomName + '/';
        };
    </script>
</body>
</html>

polls/templates/polls/details.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="../../polls/">
    Poll Application
  </a>
</nav>
<h1>   Question: {{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:voting' question.id %}" method="post">
{% csrf_token %}
<div class="form-check">
{% for choice in question.choice_set.all %}
    <input  class="form-check-label" type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label class="form-check-label" for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}

<input type="submit" value="Vote" class="btn btn-primary"/>
</div>
</form>

polls/templates/polls/index.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<div class="container-fluid">
  <!-- Content here -->

<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="/polls/">
    Poll Application
  </a>
</nav>

{% if latest_question_list %}
    <ul class="list-group">
    {% for question in latest_question_list %}
    <li class="list-group-item"><a href="{% url 'polls:details' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
</div>

polls/templates/polls/results.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="../../../polls/">
    Poll Application
  </a>
</nav>
<div class="container-fluid">

<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li class="list-group-item">{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a class="btn btn-primary" href="{% url 'polls:details' question.id %}">Vote again?</a>
</div>